# Config
# github:         [Repository metadata]
highlighter:    pygments
timezone:       "Asia/Jakarta"
encoding:       "utf-8"
exclude:        ['node_modules', 'bower_components', 'Gulpfile.js', '*.json']
include:        [.htaccess]
keepfiles:      ['assets']
markdown:       kramdown
permalink:      pretty
future:         false
baseurl:        ""


# Site settings
title:          de@aria
